# We are going to start TensorFlow Basics here

In [13]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [14]:
print(tf.__version__)

2.19.0


In [15]:
#Creatint Tensor with constant
#function here that we can use to create string
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [16]:
scalar.ndim

0

In [19]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [20]:
vector.ndim

1

In [22]:
matrix = tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [23]:
matrix.ndim

2

In [28]:
second_matrix = tf.constant([[5,7],
                             [3,8],
                             [3,9],
                             [4,2],
                             [8,6]])

second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [29]:
second_matrix.ndim

2

In [31]:
third_matrix=tf.constant(
    [
        [[1,2,3],
        [2,4,5]],

        [[1,2,3],
        [2,4,5]],

        [[1,2,3],
        [2,4,5]],
        ])

third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 4, 5]],

       [[1, 2, 3],
        [2, 4, 5]],

       [[1, 2, 3],
        [2, 4, 5]]], dtype=int32)>

In [32]:
third_matrix.ndim

3

In [33]:
second_matrix = tf.constant([[5,7],
                             [3,8],
                             [3,9],
                             [4,2],
                             [8,6]],dtype = tf.float16)
print(second_matrix)

tf.Tensor(
[[5. 7.]
 [3. 8.]
 [3. 9.]
 [4. 2.]
 [8. 6.]], shape=(5, 2), dtype=float16)


# Find the shape,rank and size of the tensors

In [34]:
#single number that means scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [41]:
print("Scalar Information")
print("Shape:",scalar.shape)
print("Dimension:",scalar.ndim)
print("Rank:",tf.rank(scalar).numpy())
print("Size:",tf.size(scalar))


Scalar Information
Shape: ()
Dimension: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [37]:
#a number with direction
vector = tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [43]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension:",vector.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [36]:
# a 2-D array of numbers
matrix = tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [44]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension:",matrix.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [38]:
#Tensor : an n-dimensional array of numbers (n=0,n=1,n=2.........)
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [45]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [46]:
# Creating Tensor using Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [47]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [48]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [49]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [50]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [54]:
# unchangeable_tensor[0].assign(12)
# unchangeable_tensor
# this will be an error bcz you cant change unchangeable tensor, it's immutable.

In [57]:
# Random Tensors
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [59]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.5452378 , 0.08562553, 0.11466372, ..., 0.5102242 , 0.53997123,
        0.5700507 ],
       [0.7945677 , 0.2563858 , 0.73860705, ..., 0.5977123 , 0.51008177,
        0.396814  ],
       [0.52060485, 0.20378351, 0.46197438, ..., 0.9354305 , 0.45431852,
        0.92083657],
       ...,
       [0.48408914, 0.02394629, 0.84153116, ..., 0.76702774, 0.9398426 ,
        0.32316518],
       [0.9090327 , 0.8074788 , 0.7951008 , ..., 0.18607795, 0.5176952 ,
        0.03916669],
       [0.14216542, 0.24761546, 0.3948394 , ..., 0.172642  , 0.0667783 ,
        0.44724894]], dtype=float32)>

In [60]:
#same seed same tensors
random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape=(3,2))

random_tensor_4 = tf.random.Generator.from_seed(42)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))

#call out data
random_tensor_3, random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [61]:
#different seed different tensors
random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape=(3,2))

random_tensor_4 = tf.random.Generator.from_seed(15)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))

#call out data
random_tensor_3, random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [63]:
#creating tensors using zeros
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [64]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [68]:
#Tensors for all ones
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [69]:
#Tensors for all ones
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.float32)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

#Converting Tensor into Numpy

In [72]:
import numpy as np
numpy_Array = np.arange(1,25,dtype=np.int32)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [76]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [79]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension:",tensor_numpy.ndim)
print("Rank:",tf.rank(tensor_numpy).numpy())
print("Size:",tf.size(tensor_numpy))
print("DataType of elements:",tensor_numpy.dtype)
print("Element along axis 0:",tensor_numpy.shape[0])
print("Element along axis 1:",tensor_numpy.shape[1])
print("Element along axis 2:",tensor_numpy.shape[2])
print("Total number of element: \t",tf.size(tensor_numpy))

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements: <dtype: 'int32'>
Element along axis 0: 2
Element along axis 1: 3
Element along axis 2: 4
Total number of element: 	 tf.Tensor(24, shape=(), dtype=int32)


In [80]:
#Working with items of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int32)>

In [82]:
#Working with first elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int32)>

**Arithmetic Operations with Tensors**

* Add
* Sub
* Multi
* Div


In [86]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [91]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [96]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [97]:
tensor_one*2
#tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [106]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [107]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [117]:
#Example
second_matrix = tf.constant([[8,16],
                             [64,8.25],
                             [625,9.23],
                             [125,2.34],
                             [169,144]],dtype=tf.float32)

second_matrix

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[  8.  ,  16.  ],
       [ 64.  ,   8.25],
       [625.  ,   9.23],
       [125.  ,   2.34],
       [169.  , 144.  ]], dtype=float32)>

In [118]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**

Create two tensors with random values between 0 and 1, shape is [6,300]

**Find out the following details:**
* Number of elements
* Size
* Rank
* Shape

In [119]:
random_tensor_first=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random_tensor_first

<tf.Tensor: shape=(6, 300), dtype=float32, numpy=
array([[0.24795139, 0.43127584, 0.6668091 , ..., 0.19377649, 0.1028477 ,
        0.7330618 ],
       [0.82505536, 0.75224066, 0.5855168 , ..., 0.20321345, 0.90732086,
        0.83149946],
       [0.14110148, 0.8601178 , 0.27312553, ..., 0.39551246, 0.18235683,
        0.701844  ],
       [0.23066592, 0.4658692 , 0.71332824, ..., 0.2935294 , 0.90195584,
        0.08557904],
       [0.00744605, 0.57805336, 0.01965749, ..., 0.17933476, 0.06538868,
        0.68917906],
       [0.85421586, 0.6432471 , 0.15451276, ..., 0.04889762, 0.80907357,
        0.09762871]], dtype=float32)>

In [121]:
print("Tensor Information")
print("Shape:",random_tensor_first.shape)
print("Rank:",tf.rank(random_tensor_first).numpy())
print("Size:",tf.size(random_tensor_first))
print("Total number of element: \t",tf.size(random_tensor_first))

Tensor Information
Shape: (6, 300)
Dimension: 2
Rank: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
DataType of elements: <dtype: 'float32'>
Element along axis 0: 6
Element along axis 1: 300
Total number of element: 	 tf.Tensor(1800, shape=(), dtype=int32)


In [122]:
random_tensor_sec=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random_tensor_sec

<tf.Tensor: shape=(6, 300), dtype=float32, numpy=
array([[0.16619384, 0.7239448 , 0.27435052, ..., 0.0666343 , 0.32971263,
        0.01971459],
       [0.0940094 , 0.36426377, 0.06666183, ..., 0.6099335 , 0.14110899,
        0.7184763 ],
       [0.92601204, 0.4899373 , 0.17285836, ..., 0.7640697 , 0.8706869 ,
        0.24462461],
       [0.09135664, 0.3994677 , 0.9690268 , ..., 0.05884123, 0.5940434 ,
        0.12481248],
       [0.7019522 , 0.03043473, 0.26460886, ..., 0.46522725, 0.6547841 ,
        0.6179105 ],
       [0.56491137, 0.4037559 , 0.2696675 , ..., 0.41193283, 0.6431706 ,
        0.00885403]], dtype=float32)>

In [124]:
print("Tensor Information")
print("Shape:",random_tensor_sec.shape)
print("Rank:",tf.rank(random_tensor_sec).numpy())
print("Size:",tf.size(random_tensor_sec))
print("Total number of element: \t",tf.size(random_tensor_sec))

Tensor Information
Shape: (6, 300)
Rank: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
Total number of element: 	 tf.Tensor(1800, shape=(), dtype=int32)
