# Numpy Introduction and usage

## we will use numpy in this jupyter notebook

# One Dimensional Array (1-D)

In [77]:
import numpy as np

In [78]:
array1=np.array([10,20,30,40,50,80,60])

In [79]:
print(array1)

[10 20 30 40 50]


# Two dimensional Array (2-D)

In [80]:
array_two=np.array([[10,20,30],[40,50,70]])

In [81]:
print(array_two)

[[10 20 30]
 [40 50 70]]


# Three dimensional Array (3-D Array)

In [82]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [83]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


## Find out dimension of NumPy Array

In [84]:
print("First Array Dimension: \t", array1.ndim)

First Array Dimension: 	 1


In [85]:
print("Second Array Dimension: \t", array_two.ndim)

Second Array Dimension: 	 2


In [86]:
print("Third Array Dimension: \t", array_three.ndim)

Third Array Dimension: 	 3


# Write an array of 5 students marks using Numpy

    ## Marks are: 80,70,75,99,89

In [87]:
array_marks=np.array([80,70,75,99,89])

In [88]:
print("Array of marks:")
print(array_marks)

Array of marks:
[80 70 75 99 89]


# Write an array to take Marks of 5 students in 3 subjects using NumPy
## Math, English, Chemistry
## [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [89]:
marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print("2-D Array example")
print(marks_subject)

2-D Array example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take Marks of 4 students for two semester using NumPy
    ## Students Name are: 'Amit','Sha','Xi','Arif'
    ## Math, English, Chemistry
    ## Two Semester: Sem1, Sem2
    ## 4*3*2
    ## [[[85,88],[78,82],[90,95]],[[80,80],[70,80],[90,90]],[[86,86],[68,62],[80,98]],[[75,87],[77,72],[97,75]]]

In [90]:
marks_subject_sem=np.array([[[85,88],[78,82],[90,95]],
                            [[80,80],[70,80],[90,90]],
                            [[86,86],[68,62],[80,98]],
                            [[75,87],[77,72],[97,75]]])

In [91]:
print(marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[80 80]
  [70 80]
  [90 90]]

 [[86 86]
  [68 62]
  [80 98]]

 [[75 87]
  [77 72]
  [97 75]]]


# Write an array: to take weather of 2 cities in 3 days for three times in a day morning, noon, evening using NumPy
    ## City Names are: Kuala Lumpur, Delhi
    ## Saturday, Sunday, Monday
    ## Three time slots: Morning, Noon, Evening
    ## 2city*3days*3timeslots
    ## Kuala Lumpur=[[23,30,24],[25,32,26],[24,31,25]]
    ## Delhi=[[20,30,19],[18,30,17],[19,31,18]]
    ## [[[23,30,24],[25,32,26],[24,31,25]],[[20,30,19],[18,30,17],[19,31,18]]]

## Create one 3-D Array using NumPy and print it

weather=np.array([[[23,30,24],[25,32,26],[24,31,25]],[[20,30,19],[18,30,17],[19,31,18]]])

In [92]:
print(weather)

[[[23 30 24]
  [25 32 26]
  [24 31 25]]

 [[20 30 19]
  [18 30 17]
  [19 31 18]]]


# Basic Information
## shape: rows and columns
## size: number of elements
## Dimension: return dimendion 1,2,3,...
## Data Type: return stored data values type

In [93]:
print(array1)

[10 20 30 40 50]


In [94]:
print("Shape of array1:",array1.shape)

Shape of array1: (5,)


In [95]:
print("Size of array1:",array1.size)

Size of array1: 5


In [96]:
print("Dimension of array1:",array1.ndim)

Dimension of array1: 1


In [97]:
print("Data Type:",array1.dtype)

Data Type: int64


In [98]:
students=np.array(["Ali","Shi","Xi","Meena","Ziva"])

In [99]:
print(students)

['Ali' 'Shi' 'Xi' 'Meena' 'Ziva']


In [100]:
print("Shape of Array:",students.shape)

Shape of Array: (5,)


In [101]:
print("Size of Array:",students.size)

Size of Array: 5


In [102]:
print("Dimension of Array:",students.ndim)

Dimension of Array: 1


In [103]:
print("Data Type:",students.dtype)
# for maximum num. of strings in data, in here <U5 from "Meena"

Data Type: <U5


In [104]:
students2=np.array(["Ali Munaf bin Kabir","Shi","Xi","Meena","Ziva"])

In [105]:
print("Data Type:",students2.dtype)
# for maximum num. of strings in data, in here <U19 from "Ali Munaf bin Kabir"

Data Type: <U19


# Mathematical Operation

In [114]:
print(array1)

[10 20 30 40 50]


In [115]:
total=np.sum(array1)

In [116]:
print(total)

150


In [117]:
print("Mean:",np.mean(array1))

Mean: 30.0


In [118]:
print("Min:",np.min(array1))

Min: 10


In [119]:
print("Max:",np.max(array1))

Max: 50


In [120]:
print("Index of Min:",np.argmin(array1))

Index of Min: 0


In [121]:
print("Index of Max:",np.argmax(array1))

Index of Max: 4


In [159]:
our_arr=np.array([100,2000,300,7000,400,500,300,1900,600])

In [123]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and sorting Example in 1 D Array

In [124]:
sorted_arr=np.sort(our_arr)

In [126]:
print("*** Sorted Array ")
print(sorted_arr)

*** Sorted Array 
[ 100  200  300  300  400  500  600 1900 7000]


In [127]:
print("Is there any item greater than 500?",np.any(sorted_arr>500))

Is there any item greater than 500? True


In [128]:
print("All greater than 500?",np.all(sorted_arr>500))

All greater than 500? False


In [129]:
print("All greater than 99?",np.all(sorted_arr>99))

All greater than 99? True


In [130]:
print("Where values >500?",np.where(sorted_arr>500))

Where values >500? (array([6, 7, 8]),)


In [131]:
print("All Number greater than 500?")
for num in np.where(sorted_arr>500):
    print(num)

All Number greater than 500?
[6 7 8]


In [132]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [133]:
print(min(our_arr))

100


In [135]:
print(np.argmin(our_arr))

0


In [136]:
print(np.argmax(our_arr))

3


In [137]:
print(np.argmax(sorted_arr))

8


In [140]:
selected_values=sorted_arr[sorted_arr>500]

In [141]:
print(selected_values)

[ 600 1900 7000]


In [146]:
for num in selected_values:
    print(num)

600
1900
7000


In [149]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [148]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


# Slicing 1 D Array
    1. To take elements from starting index to end index
    2. e.g.[start:end]

In [160]:
print(our_arr)

[ 100 2000  300 7000  400  500  300 1900  600]


In [161]:
sorted_arr=np.sort(our_arr)
print(np.sort(our_arr))

[ 100  300  300  400  500  600 1900 2000 7000]


## starting from an index 1  to 2

In [162]:
slice_sorted_arr=sorted_arr[1:3]
print(slice_sorted_arr)

[300 300]


## starting from an index 3 going to the end

In [164]:
print(sorted_arr[3:])

[ 400  500  600 1900 2000 7000]


## starting from beginning index going to the forth(0,1,2,3)

In [167]:
print(sorted_arr[:4])

[100 300 300 400]


In [166]:
print(sorted_arr[:5])

[100 300 300 400 500]


## step
    ## [start:end step]
    ## step: every step element

In [170]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[300 400 600]


In [174]:
print("Original Array")
print(sorted_arr)
print("Every Third Element")
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  300  300  400  500  600 1900 2000 7000]
Every Third Element
[ 100  400 1900]


# Slice Reverse

In [176]:
print("Original Array")
print(sorted_arr)
print("Reverse Array:")
print(sorted_arr[::-1])

Original Array
[ 100  300  300  400  500  600 1900 2000 7000]
Reverse Array:
[7000 2000 1900  600  500  400  300  300  100]


In [177]:
print("Last Five Element")
print(sorted_arr[-5:])

Last Five Element
[ 500  600 1900 2000 7000]


In [178]:
print("Slicing Done")

Slicing Done
