In [2]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_excel("students.xlsx")
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [13]:
marks=df["Marks"].to_numpy()
print("Numpy Array of Marks")
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [14]:
print("Highest Marks",np.max(marks))

Highest Marks 92


In [17]:
print("Lowest Marks",np.min(marks))

Lowest Marks 45


In [16]:
print("Average Marks",np.mean(marks))

Average Marks 80.0


## .loc: Label Based

In [32]:
print("Original Dataframe")
print(df)
print("Location:Label Based")
print(df.loc[3,["Name","Marks"]])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location:Label Based
Name     Sara
Marks      92
Name: 3, dtype: object


## .iloc: Index Based

In [31]:
print("Original Dataframe")
print(df)
print("Location:Index Based")
print(df.iloc[3,[1,2]])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location:Index Based
Age      23
Marks    92
Name: 3, dtype: object


# Axis in Numpy
    1. Axis 0 : vertical directions: works column wise
    2. Axis 1 :horizontal direction: works row-wise

## we have two students marks in 3 subjects
    #[[45,50,49],[30,45,49]]

In [33]:
marks_arr=np.array([[45,50,49],[30,45,49]])
print(marks_arr)

[[45 50 49]
 [30 45 49]]


In [34]:
print("Sum down each column",np.sum(marks_arr,axis=0))

Sum down each column [75 95 98]


In [35]:
print("Sum down each row",np.sum(marks_arr,axis=1))

Sum down each row [144 124]


In [36]:
print("Numpy Array of Marks")
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [37]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


## Find the Student Name who got highest marks

In [44]:
top_index = df["Marks"].idxmax()
print(top_index)

3


In [40]:
topper=df.loc[df["Marks"].idxmax(),"Name"]
print(topper)

Sara


In [41]:
lastinclass=df.loc[df["Marks"].idxmin(),"Name"]
print(lastinclass)

Rohit


In [42]:
print("Next Example")

Next Example


In [47]:
top_index = df["Marks"].idxmax()
top_student=df.iloc[top_index,df.columns.get_loc("Name")]
print("Topper of the class is:",top_student)

Topper of the class is: Sara
